version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: conduit_admin
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: conduit-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # api:
  #     build:
  #       context: ./service
  #       dockerfile: Dockerfile
  #     restart: always
  #     ports:
  #       - '3456:3456'
