version: '3'

services:
  cockroachdb:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - start
      - --insecure
      - --certs-dir=/cockroach/certs
      - --join=cockroachdb
      - --advertise-addr=cockroachdb
      - --http-addr=0.0.0.0:8080
      # - --sql-addr=0.0.0.0:26257
      # - --listen-addr=0.0.0.0:26257

    ports:
      - "8080:8080"
      - "26257:26257"
    environment:
      COCKROACH_USER: root
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./certs:/cockroach/certs:ro
    networks:
      cockroach_network:
        ipv4_address: 172.28.1.1

volumes:
  cockroach-data:

networks:
  cockroach_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
