# Use the official PostgreSQL image as the base
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=prisma
ENV POSTGRES_PASSWORD=prisma
ENV POSTGRES_DB=conduit-coffee

# Expose the default PostgreSQL port
EXPOSE 5432
