app = "conduit-db"
primary_region = "lax"

[build]

[database]
  engine = "postgres"
  name = "conduit_db"
  region = "lax"

[[services]]
  internal_port = 5432
  protocol = "tcp"

[[services.ports]]
    port = 5432
